networks:
  apps:
#    name: apps
    driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - "/dev/video0:/dev/video0"
    image: face-detect:latest
    # env_file:
    #   - .env
#    container_name: mm-pddikti-be >>> #untuk penamaan container kubernetes
    tty: true
    ports:
      - "9001:5000"
    restart: unless-stopped
    networks:
      - apps
#    volumes:
#      - .env:/app/.env


